AWSTemplateFormatVersion: '2010-09-09'
Description: AnswerKing API
Transform: AWS::Serverless-2016-10-31

Parameters:
  DeployedByTag:
    Description: Standard deploy tag
    Type: String
    Default: Muaaz

Resources:
  CreateCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Categories/create_category.lambda_handler
      Runtime: python3.13
      Events:
        CreateCategoryAPI:
          Type: Api
          Properties:
            Path: /categories
            Method: POST
      Policies:
        - DynamoDBWritePolicy:
            TableName: AnswerKingDB
      Tags:
        Project: AnswerKing
        deployed-by: !Ref DeployedByTag

  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Items/create_item.lambda_handler
      Runtime: python3.13
      Events:
        CreateItemAPI:
          Type: Api
          Properties:
            Path: /items
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: AnswerKingDB
      Tags:
        Project: AnswerKing
        deployed-by: !Ref DeployedByTag

  ViewItemsByCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Categories/view_items_by_category.lambda_handler
      Runtime: python3.13
      Events:
        ApiGetItemsByCategory:
          Type: Api
          Properties:
            Path: /categories/{category_id}/items
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: AnswerKingDB
      Tags:
        Project: AnswerKing
        deployed-by: !Ref DeployedByTag

  ViewAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Items/view_items.lambda_handler
      Runtime: python3.13
      Events:
        ApiGetItems:
          Type: Api
          Properties:
            Path: /items
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: AnswerKingDB
      Tags:
        Project: AnswerKing
        deployed-by: !Ref DeployedByTag

  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Items/delete_items.lambda_handler
      Runtime: python3.13
      Events:
        DeleteItemAPI:
          Type: Api
          Properties:
            Path: /categories/{category_id}/items/{item_id}
            Method: PATCH
      Policies:
        - DynamoDBCrudPolicy:
            TableName: AnswerKingDB
      Tags:
        Project: AnswerKing
        deployed-by: !Ref DeployedByTag

  DeleteCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Categories/delete_category.lambda_handler
      Runtime: python3.13
      Events:
        DeleteCategoryAPI:
          Type: Api
          Properties:
            Path: /categories/{category_id}
            Method: PATCH
      Policies:
        - DynamoDBCrudPolicy:
            TableName: AnswerKingDB
      Tags:
        Project: AnswerKing
        deployed-by: !Ref DeployedByTag

  ViewAllCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Categories/view_categories.lambda_handler
      Runtime: python3.13
      Events:
        ApiGetCategories:
          Type: Api
          Properties:
            Path: /categories
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: AnswerKingDB
      Tags:
        Project: AnswerKing
        deployed-by: !Ref DeployedByTag

  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Items/update_item.lambda_handler
      Runtime: python3.13
      Events:
        UpdateItemAPI:
          Type: Api
          Properties:
            Path: /categories/{category_id}/items/{item_id}
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: AnswerKingDB
      Tags:
        Project: AnswerKing
        deployed-by: !Ref DeployedByTag  

  UpdateCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Categories/update_category.lambda_handler
      Runtime: python3.13
      Events:
        UpdateCategoryAPI:
          Type: Api
          Properties:
            Path: /categories/{category_id}
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: AnswerKingDB
      Tags:
        Project: AnswerKing
        deployed-by: !Ref DeployedByTag  

Outputs:
  CreateCategoryApiUrl:
    Description: "API Gateway endpoint URL for creating categories // POST"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categories"

  CreateItemApiUrl:
    Description: "API Gateway endpoint URL for creating items // POST"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items"

  GetItemsByCategoryApiUrl:
    Description: "API Gateway endpoint URL for viewing items by category // GET"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categories/{category_id}/items"

  GetItemsApiUrl:
    Description: "API Gateway endpoint URL for viewing all items // GET"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items"

  DeleteItemApiUrl:
    Description: "API Gateway endpoint URL for deleting item // PATCH"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categories/{category_id}/items/{item_id}"

  DeleteCategoryApiUrl:
    Description: "API Gateway endpoint URL for deleting category // PATCH"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categories/{category_id}"

  ViewAllCategoriesApiUrl:
    Description: "API Gateway endpoint URL for viewing all categories // GET"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categories"

  UpdateItemApiUrl:
    Description: "API Gateway endpoint URL for update item // PUT"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categories/{category_id}/items/{item_id}"

  UpdateCategoryApiUrl:
    Description: "API Gateway endpoint URL for updating category // PUT"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/categories/{category_id}"